#!/bin/sh
set -e

cd $(dirname $0)

make_args=$@

SRC_DIR=$PWD/..
LOCAL_PROPERTIES=$SRC_DIR/local.properties

if [ ! -e "$LOCAL_PROPERTIES" ]; then
    echo "Creating $LOCAL_PROPERTIES"
    # Must match ci/install-android-sdk
    echo "sdk.dir=/opt/android-sdk" > "$LOCAL_PROPERTIES"
fi

if [ -z "$KEYSTORE_BASE64" ]; then
    echo "Can't sign: \$KEYSTORE_BASE64 environment variable not set."

    docker run --rm \
    -v $SRC_DIR:/src/pixelwheels \
    pixelwheels \
    -c "make GRADLEW='./gradlew --console plain' -C /src/pixelwheels clean-dist $make_args"
else
    docker run --rm \
    -v $SRC_DIR:/src/pixelwheels \
    --env "KEYSTORE_BASE64=$KEYSTORE_BASE64" \
    --env "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" \
    --env "KEYSTORE_KEY_ALIAS=$KEYSTORE_KEY_ALIAS" \
    --env "KEYSTORE_KEY_PASSWORD=$KEYSTORE_KEY_PASSWORD" \
    pixelwheels \
    -c "make GRADLEW='./gradlew --console plain' -C /src/pixelwheels clean-dist $make_args"
fi

